project:
  title: "Project Loon"
  type: datapage

website:
  page-footer:
    background: light
    left: |
      Made with [datapages](https://datapages.github.io) using [Quarto](https://quarto.org/) and [Observable](https://observablehq.com/), with support from the National Science Foundation.
    center: ""
    right: 
      - icon: github
        href: https://github.com/datapages/project-loon

format:
  datapage-html:
    theme:
      - resources/scss/main.scss
      - resources/scss/modal.scss
    mainfont: Source Sans Pro
    title-block-banner: false
    anchor-sections: false

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: sdss
  dataset: project_loon
  table: loon
